/**
 * The service worker, as a template the build fills in.
 *
 * Offline first, and deliberately not clever about it. Everything the app is made of is precached on
 * install and served from that cache thereafter; the network is only consulted to *find out whether a new
 * version exists*, never to render the page. A tool used while crouched next to a battery on a balcony
 * cannot depend on the Wi-Fi it is there to configure.
 *
 * ## Why the file list is generated
 *
 * Bun hashes its chunks, so the names change with the content. A hand-written list would go stale silently:
 * the worker would precache a chunk that no longer exists, installation would fail, and the app would keep
 * running from the old cache with no sign that anything was wrong. Generating the list from the build's own
 * output makes that impossible.
 *
 * ## Updating is offered, never imposed
 *
 * A new worker installs and then waits. It does not replace the running one until the page asks, because
 * swapping the app out from under someone half way through a sweep of 146 parameters would lose their
 * readings. The page checks for an update on load and shows a button; this worker acts only when told.
 */

/** Built from the actual output. */
export function serviceWorker(cacheName: string, assets: readonly string[]): string {
  const list = assets.map((asset) => `  ${JSON.stringify(asset)},`).join("\n");
  return `/* Generated by scripts/build.ts. Edit scripts/service-worker.ts instead. */
const CACHE = ${JSON.stringify(cacheName)};

const ASSETS = [
${list}
];

self.addEventListener("install", (event) => {
  // No skipWaiting here: a fresh worker waits until the page asks for it.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      // Every build gets its own cache, so activation is also the only cleanup there is.
      const names = await caches.keys();
      await Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);

      // A navigation is answered with the app shell whatever the path, so a reload deep in the app works
      // offline and an unknown path does not produce the browser's error page.
      if (request.mode === "navigate") {
        return (await cache.match("./")) ?? (await cache.match("./index.html")) ?? fetch(request);
      }

      const hit = await cache.match(request);
      if (hit) return hit;

      // Not precached — an icon a manifest asked for late, say. Fetch it and keep it.
      //
      // A failure here is allowed to be a failure. This used to answer with the app shell instead, which
      // meant an image request could be satisfied with HTML: the browser reports that as "icon failed to
      // load" against a URL that is perfectly good, and the real cause — that the fetch never happened —
      // is hidden. Only a navigation may be answered with the shell, and that is handled above.
      const response = await fetch(request);
      if (response.ok) await cache.put(request, response.clone());
      return response;
    })(),
  );
});

self.addEventListener("message", (event) => {
  // The one thing the page may command: stop waiting and take over. The page reloads itself when the
  // controller changes.
  if (event.data === "take-over") void self.skipWaiting();
});
`;
}
